/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardRosterRouteImport } from './routes/dashboard.roster'
import { Route as DashboardRequestLeaveRouteImport } from './routes/dashboard.request-leave'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardLeavesRouteImport } from './routes/dashboard.leaves'
import { Route as DashboardIdCardRouteImport } from './routes/dashboard.id-card'
import { Route as DashboardFeesRouteImport } from './routes/dashboard.fees'
import { Route as DashboardChildrenRouteImport } from './routes/dashboard.children'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRosterRoute = DashboardRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestLeaveRoute = DashboardRequestLeaveRouteImport.update({
  id: '/request-leave',
  path: '/request-leave',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeavesRoute = DashboardLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIdCardRoute = DashboardIdCardRouteImport.update({
  id: '/id-card',
  path: '/id-card',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeesRoute = DashboardFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChildrenRoute = DashboardChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/children': typeof DashboardChildrenRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/id-card': typeof DashboardIdCardRoute
  '/dashboard/leaves': typeof DashboardLeavesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/request-leave': typeof DashboardRequestLeaveRoute
  '/dashboard/roster': typeof DashboardRosterRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/children': typeof DashboardChildrenRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/id-card': typeof DashboardIdCardRoute
  '/dashboard/leaves': typeof DashboardLeavesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/request-leave': typeof DashboardRequestLeaveRoute
  '/dashboard/roster': typeof DashboardRosterRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/children': typeof DashboardChildrenRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/id-card': typeof DashboardIdCardRoute
  '/dashboard/leaves': typeof DashboardLeavesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/request-leave': typeof DashboardRequestLeaveRoute
  '/dashboard/roster': typeof DashboardRosterRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/superadmin'
    | '/dashboard/account'
    | '/dashboard/activity'
    | '/dashboard/attendance'
    | '/dashboard/children'
    | '/dashboard/fees'
    | '/dashboard/id-card'
    | '/dashboard/leaves'
    | '/dashboard/payments'
    | '/dashboard/request-leave'
    | '/dashboard/roster'
    | '/dashboard/students'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/superadmin'
    | '/dashboard/account'
    | '/dashboard/activity'
    | '/dashboard/attendance'
    | '/dashboard/children'
    | '/dashboard/fees'
    | '/dashboard/id-card'
    | '/dashboard/leaves'
    | '/dashboard/payments'
    | '/dashboard/request-leave'
    | '/dashboard/roster'
    | '/dashboard/students'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/superadmin'
    | '/dashboard/account'
    | '/dashboard/activity'
    | '/dashboard/attendance'
    | '/dashboard/children'
    | '/dashboard/fees'
    | '/dashboard/id-card'
    | '/dashboard/leaves'
    | '/dashboard/payments'
    | '/dashboard/request-leave'
    | '/dashboard/roster'
    | '/dashboard/students'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SuperadminRoute: typeof SuperadminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roster': {
      id: '/dashboard/roster'
      path: '/roster'
      fullPath: '/dashboard/roster'
      preLoaderRoute: typeof DashboardRosterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/request-leave': {
      id: '/dashboard/request-leave'
      path: '/request-leave'
      fullPath: '/dashboard/request-leave'
      preLoaderRoute: typeof DashboardRequestLeaveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leaves': {
      id: '/dashboard/leaves'
      path: '/leaves'
      fullPath: '/dashboard/leaves'
      preLoaderRoute: typeof DashboardLeavesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/id-card': {
      id: '/dashboard/id-card'
      path: '/id-card'
      fullPath: '/dashboard/id-card'
      preLoaderRoute: typeof DashboardIdCardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fees': {
      id: '/dashboard/fees'
      path: '/fees'
      fullPath: '/dashboard/fees'
      preLoaderRoute: typeof DashboardFeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/children': {
      id: '/dashboard/children'
      path: '/children'
      fullPath: '/dashboard/children'
      preLoaderRoute: typeof DashboardChildrenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardChildrenRoute: typeof DashboardChildrenRoute
  DashboardFeesRoute: typeof DashboardFeesRoute
  DashboardIdCardRoute: typeof DashboardIdCardRoute
  DashboardLeavesRoute: typeof DashboardLeavesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardRequestLeaveRoute: typeof DashboardRequestLeaveRoute
  DashboardRosterRoute: typeof DashboardRosterRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardChildrenRoute: DashboardChildrenRoute,
  DashboardFeesRoute: DashboardFeesRoute,
  DashboardIdCardRoute: DashboardIdCardRoute,
  DashboardLeavesRoute: DashboardLeavesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardRequestLeaveRoute: DashboardRequestLeaveRoute,
  DashboardRosterRoute: DashboardRosterRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SuperadminRoute: SuperadminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
